<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="0" failed="2" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-12-03T23:54:49 EST" name="Suite" finished-at="2021-12-03T23:55:39 EST" duration-ms="50494">
    <groups>
    </groups>
    <test started-at="2021-12-03T23:54:49 EST" name="AddUser" finished-at="2021-12-03T23:55:21 EST" duration-ms="32809">
      <class name="com.teladoc.challenge.testScripts.AddUserTest">
        <test-method is-config="true" signature="openBrowser(java.lang.String)[pri:0, instance:com.teladoc.challenge.testScripts.AddUserTest@73e22a3d]" started-at="2021-12-03T23:54:49 EST" name="openBrowser" finished-at="2021-12-03T23:55:01 EST" duration-ms="12608" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[http://www.way2automation.com/angularjs-protractor/webtables/]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openBrowser -->
        <test-method signature="verifyAddUser(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:com.teladoc.challenge.testScripts.AddUserTest@73e22a3d]" started-at="2021-12-03T23:55:01 EST" name="verifyAddUser" finished-at="2021-12-03T23:55:18 EST" duration-ms="16256" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[http://www.way2automation.com/angularjs-protractor/webtables/]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Astha]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Pandita]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[astha]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[Customer]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[asthap@gmail.com]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[1234567890]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[User Not Added expected [1] but found [0]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: User Not Added expected [1] but found [0]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:907)
at com.teladoc.challenge.testScripts.AddUserTest.verifyAddUser(AddUserTest.java:85)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyAddUser -->
        <test-method is-config="true" signature="afterTest()[pri:0, instance:com.teladoc.challenge.testScripts.AddUserTest@73e22a3d]" started-at="2021-12-03T23:55:18 EST" name="afterTest" finished-at="2021-12-03T23:55:21 EST" duration-ms="3879" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
      </class> <!-- com.teladoc.challenge.testScripts.AddUserTest -->
    </test> <!-- AddUser -->
    <test started-at="2021-12-03T23:55:22 EST" name="DeleteUser" finished-at="2021-12-03T23:55:39 EST" duration-ms="17613">
      <class name="com.teladoc.challenge.testScripts.DeleteUserTest">
        <test-method is-config="true" signature="openBrowser(java.lang.String)[pri:0, instance:com.teladoc.challenge.testScripts.DeleteUserTest@506ae4d4]" started-at="2021-12-03T23:55:22 EST" name="openBrowser" finished-at="2021-12-03T23:55:35 EST" duration-ms="13024" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[http://www.way2automation.com/angularjs-protractor/webtables/]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openBrowser -->
        <test-method signature="deleteUser(java.lang.String,java.lang.String)[pri:0, instance:com.teladoc.challenge.testScripts.DeleteUserTest@506ae4d4]" started-at="2021-12-03T23:55:35 EST" name="deleteUser" finished-at="2021-12-03T23:55:37 EST" duration-ms="2464" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[http://www.way2automation.com/angularjs-protractor/webtables/]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[novak]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[User Not Deleted expected [0] but found [1]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: User Not Deleted expected [0] but found [1]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:907)
at com.teladoc.challenge.testScripts.DeleteUserTest.deleteUser(DeleteUserTest.java:67)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- deleteUser -->
        <test-method is-config="true" signature="afterTest()[pri:0, instance:com.teladoc.challenge.testScripts.DeleteUserTest@506ae4d4]" started-at="2021-12-03T23:55:37 EST" name="afterTest" finished-at="2021-12-03T23:55:39 EST" duration-ms="2118" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
      </class> <!-- com.teladoc.challenge.testScripts.DeleteUserTest -->
    </test> <!-- DeleteUser -->
  </suite> <!-- Suite -->
</testng-results>
